name: Deploying angular app to S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "23"
      - name: Set Shell Environment Variable
        run: |
          echo $SHELL
          echo "SHELL=/bin/bash" >> $GITHUB_ENV
          export SHELL=/bin/bash

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm setup
          echo 'export PNPM_HOME=$HOME/.local/share/pnpm' >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
          echo 'export PATH=$PNPM_HOME:$PATH' >> ~/.bashrc
          source ~/.bashrc

      - name: Install packages and dependencies
        run: |
          pnpm -v
          pnpm install -g @angular/cli && pnpm install

      - name: Run build
        run: pnpm run build
