name: Deploying angular app to S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          version: "10"
          run_install: false
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install packages and dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build
