name: Deploying angular app to S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          version: "10"
          run_install: false
      - name: Install NodeJS ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "pnpm"

      - name: Install packages and dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist/first-angular-app

  deploy:
    name: Development to S3 and CloudFront
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: dist/first-angular-app
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: S3 Sync
        run: aws s3 sync dist/first-angular-app s3://${{ secrets.S3_BUCKET }} --delete

      - name: Cloudfront Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
